using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class test : MonoBehaviour
{
    // Start is called before the first frame update
    void Start()
    {
        
    }

    private void OnDrawGizmos()
    {
        
    } 
    // Update is called once per frame
    void Update()
    {
        //float horizontal = Input.GetAxis("Horizontal3");
        //float vertical = Input.GetAxis("Vertical3");
        //Vector3 direction = new Vector3(horizontal, 0, -vertical).normalized;
        //this.transform.rotation = Quaternion.LookRotation(Vector3.up, direction);

        //this.transform.position += Vector3.forward * -10 * Time.deltaTime;
    }
}
